-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.6.0.83.4
-- Module  Version: 5.8
--C:\lscc\diamond\3.6_x64\ispfpga\bin\nt64\scuba.exe -w -n rx_mux -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type iol -mode in -io_type LVCMOS25 -width 1 -freq_in 250 -gear 4 -clk eclk -del 64 

-- Thu Oct 29 19:51:17 2015

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity rx_mux is
    port (
        alignwd: in  std_logic; 
        clk: in  std_logic; 
        clk_s: in  std_logic; 
        del: in  std_logic_vector(4 downto 0); 
        init: in  std_logic; 
        reset: in  std_logic; 
        rx_ready: out  std_logic; 
        sclk: out  std_logic; 
        datain: in  std_logic_vector(0 downto 0); 
        q: out  std_logic_vector(7 downto 0));
end rx_mux;

architecture Structure of rx_mux is

    -- internal signal declarations
    signal scuba_vlo: std_logic;
    signal opensync_0: std_logic;
    signal opensync_1: std_logic;
    signal opensync_cken: std_logic;
    signal opensync_2: std_logic;
    signal q7_0: std_logic;
    signal q6_0: std_logic;
    signal q5_0: std_logic;
    signal q4_0: std_logic;
    signal q3_0: std_logic;
    signal q2_0: std_logic;
    signal q1_0: std_logic;
    signal q0_0: std_logic;
    signal sclk_t: std_logic;
    signal cdiv1: std_logic;
    signal eclko: std_logic;
    signal xstop: std_logic;
    signal xstart: std_logic;
    signal opensync_3: std_logic;
    signal eclki: std_logic;
    signal lock_chk: std_logic;
    signal scuba_vhi: std_logic;
    signal dataini_t0: std_logic;
    signal buf_clk: std_logic;
    signal buf_dataini0: std_logic;

    -- local component declarations
    component FD1P3BX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component IB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    component IDDRX4B
        port (D: in  std_logic; ECLK: in  std_logic; SCLK: in  std_logic; 
            RST: in  std_logic; ALIGNWD: in  std_logic; 
            Q0: out  std_logic; Q1: out  std_logic; Q2: out  std_logic; 
            Q3: out  std_logic; Q4: out  std_logic; Q5: out  std_logic; 
            Q6: out  std_logic; Q7: out  std_logic);
    end component;
    component DELAYD
        port (A: in  std_logic; DEL4: in  std_logic; DEL3: in  std_logic; 
            DEL2: in  std_logic; DEL1: in  std_logic; 
            DEL0: in  std_logic; Z: out  std_logic);
    end component;
    component CLKDIVC
        generic (DIV : in String);
        port (RST: in  std_logic; CLKI: in  std_logic; 
            ALIGNWD: in  std_logic; CDIV1: out  std_logic; 
            CDIVX: out  std_logic);
    end component;
    component ECLKSYNCA
        port (ECLKI: in  std_logic; STOP: in  std_logic; 
            ECLKO: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute IO_TYPE : string; 
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute IO_TYPE of Inst2_IB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    LUT4_1: ROM16X1A
        generic map (initval=> X"0a78")
        port map (AD3=>opensync_0, AD2=>opensync_3, AD1=>lock_chk, 
            AD0=>init, DO0=>opensync_cken);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    LUT4_0: ROM16X1A
        generic map (initval=> X"fffe")
        port map (AD3=>opensync_0, AD2=>opensync_1, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>xstop);

    FF_3: FD1P3BX
        port map (D=>opensync_3, SP=>opensync_cken, CK=>clk_s, PD=>reset, 
            Q=>opensync_0);

    FF_2: FD1P3DX
        port map (D=>opensync_0, SP=>opensync_cken, CK=>clk_s, CD=>reset, 
            Q=>opensync_1);

    FF_1: FD1P3DX
        port map (D=>opensync_1, SP=>opensync_cken, CK=>clk_s, CD=>reset, 
            Q=>opensync_2);

    FF_0: FD1P3DX
        port map (D=>opensync_2, SP=>opensync_cken, CK=>clk_s, CD=>reset, 
            Q=>opensync_3);

    Inst5_IDDRX4B0: IDDRX4B
        port map (D=>dataini_t0, ECLK=>eclko, SCLK=>sclk_t, RST=>reset, 
            ALIGNWD=>alignwd, Q0=>q0_0, Q1=>q1_0, Q2=>q2_0, Q3=>q3_0, 
            Q4=>q4_0, Q5=>q5_0, Q6=>q6_0, Q7=>q7_0);

    Inst4_CLKDIVC: CLKDIVC
        generic map (DIV=> "4.0")
        port map (RST=>reset, CLKI=>eclko, ALIGNWD=>alignwd, 
            CDIV1=>cdiv1, CDIVX=>sclk_t);

    Inst3_ECLKSYNCA: ECLKSYNCA
        port map (ECLKI=>eclki, STOP=>xstop, ECLKO=>eclko);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    udel_dataini0: DELAYD
        port map (A=>buf_dataini0, DEL4=>del(4), DEL3=>del(3), 
            DEL2=>del(2), DEL1=>del(1), DEL0=>del(0), Z=>dataini_t0);

    Inst2_IB: IB
        port map (I=>clk, O=>buf_clk);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= sclk_t;
    q(7) <= q7_0;
    q(6) <= q6_0;
    q(5) <= q5_0;
    q(4) <= q4_0;
    q(3) <= q3_0;
    q(2) <= q2_0;
    q(1) <= q1_0;
    q(0) <= q0_0;
    rx_ready <= xstart;
    xstart <= opensync_3;
    eclki <= buf_clk;
    lock_chk <= scuba_vhi;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of rx_mux is
    for Structure
        for all:FD1P3BX use entity MACHXO2.FD1P3BX(V); end for;
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:ROM16X1A use entity MACHXO2.ROM16X1A(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:IB use entity MACHXO2.IB(V); end for;
        for all:IDDRX4B use entity MACHXO2.IDDRX4B(V); end for;
        for all:DELAYD use entity MACHXO2.DELAYD(V); end for;
        for all:CLKDIVC use entity MACHXO2.CLKDIVC(V); end for;
        for all:ECLKSYNCA use entity MACHXO2.ECLKSYNCA(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
